[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]
